import streamlit as st
import random

# --- 1. KHO DỮ LIỆU TỔNG HỢP 275 TỪ (11 NHÓM) ---
vocab_db = [
    # Nhóm 1-7
    {"h": "熊猫", "p": "xióngmāo", "m": "Gấu trúc"}, {"h": "刚才", "p": "gāngcái", "m": "Vừa nãy"},
    {"h": "蓝", "p": "lán", "m": "Màu xanh da trời"}, {"h": "终于", "p": "zhōngyú", "m": "Cuối cùng thì"},
    {"h": "简单", "p": "jiǎndān", "m": "Đơn giản"}, {"h": "礼物", "p": "lǐwù", "m": "Quà tặng"},
    {"h": "愿意", "p": "yuànyì", "m": "Sẵn lòng/Bằng lòng"}, {"h": "洗手间", "p": "xǐshǒujiān", "m": "Nhà vệ sinh"},
    {"h": "西", "p": "xī", "m": "Phía Tây"}, {"h": "经理", "p": "jīnglǐ", "m": "Giám đốc/Quản lý"},
    {"h": "历史", "p": "lìshǐ", "m": "Lịch sử"}, {"h": "画", "p": "huà", "m": "Vẽ/Bức tranh"},
    {"h": "故事", "p": "gùshì", "m": "Câu chuyện"}, {"h": "还是", "p": "háishi", "m": "Hoặc là (câu hỏi)/Vẫn"},
    {"h": "低", "p": "dī", "m": "Thấp"}, {"h": "以前", "p": "yǐqián", "m": "Trước đây"},
    {"h": "几乎", "p": "jīhū", "m": "Hầu như/Suýt nữa"}, {"h": "检查", "p": "jiǎnchá", "m": "Kiểm tra"},
    {"h": "结婚", "p": "jiéhūn", "m": "Kết hôn"}, {"h": "记得", "p": "jìde", "m": "Nhớ"},
    {"h": "经常", "p": "jīngcháng", "m": "Thường xuyên"}, {"h": "解决", "p": "jiějué", "m": "Giải quyết"},
    {"h": "借", "p": "jiè", "m": "Mượn/Vay"}, {"h": "决定", "p": "juédìng", "m": "Quyết định"},
    {"h": "可爱", "p": "kě'ài", "m": "Đáng yêu"},
    {"h": "阿姨", "p": "āyí", "m": "Dì/Cô"}, {"h": "突然", "p": "tūrán", "m": "Đột nhiên"},
    {"h": "干净", "p": "gānjìng", "m": "Sạch sẽ"}, {"h": "明白", "p": "míngbai", "m": "Hiểu/Rõ ràng"},
    {"h": "胖", "p": "pàng", "m": "Béo"}, {"h": "相信", "p": "xiāngxìn", "m": "Tin tưởng"},
    {"h": "太阳", "p": "tàiyáng", "m": "Mặt trời"}, {"h": "打算", "p": "dǎsuàn", "m": "Dự định/Kế hoạch"},
    {"h": "发现", "p": "fāxiàn", "m": "Phát hiện"}, {"h": "同事", "p": "tóngshì", "m": "Đồng nghiệp"},
    {"h": "兴趣", "p": "xìngqù", "m": "Hứng thú/Sở thích"}, {"h": "舒服", "p": "shūfu", "m": "Thoải mái/Dễ chịu"},
    {"h": "变化", "p": "biànhuà", "m": "Thay đổi/Biến hóa"}, {"h": "饮料", "p": "yǐnliào", "m": "Đồ uống"},
    {"h": "特别", "p": "tèbié", "m": "Đặc biệt"}, {"h": "相同", "p": "xiāngtóng", "m": "Giống nhau"},
    {"h": "奇怪", "p": "qíguài", "m": "Kỳ lạ"}, {"h": "热情", "p": "rèqíng", "m": "Nhiệt tình"},
    {"h": "必须", "p": "bìxū", "m": "Bắt buộc/Phải"}, {"h": "只有", "p": "zhǐyǒu", "m": "Chỉ có"},
    {"h": "总是", "p": "zǒngshì", "m": "Luôn luôn"}, {"h": "担心", "p": "dānxīn", "m": "Lo lắng"},
    {"h": "举行", "p": "jǔxíng", "m": "Tổ chức/Cử hành"}, {"h": "世界", "p": "shìjiè", "m": "Thế giới"},
    {"h": "准备", "p": "zhǔnbèi", "m": "Chuẩn bị"},
    {"h": "草", "p": "cǎo", "m": "Cỏ"}, {"h": "层", "p": "céng", "m": "Tầng/Lớp"},
    {"h": "差", "p": "chà", "m": "Kém/Tồi"}, {"h": "声音", "p": "shēngyīn", "m": "Âm thanh/Tiếng nói"},
    {"h": "衬衫", "p": "chènshān", "m": "Áo sơ mi"}, {"h": "成绩", "p": "chéngjì", "m": "Thành tích/Kết quả"},
    {"h": "城市", "p": "chéngshì", "m": "Thành phố"}, {"h": "迟到", "p": "chídào", "m": "Đến muộn"},
    {"h": "出现", "p": "chūxiàn", "m": "Xuất hiện"}, {"h": "厨房", "p": "chúfáng", "m": "Nhà bếp"},
    {"h": "除了", "p": "chúle", "m": "Ngoài... ra"}, {"h": "词典", "p": "cídiǎn", "m": "Từ điển"},
    {"h": "聪明", "p": "cōngming", "m": "Thông minh"}, {"h": "打扫", "p": "dǎsǎo", "m": "Quét dọn/Vệ sinh"},
    {"h": "蛋糕", "p": "dàngāo", "m": "Bánh ngọt"}, {"h": "当然", "p": "dāngrán", "m": "Đương nhiên"},
    {"h": "灯", "p": "dēng", "m": "Đèn"}, {"h": "地方", "p": "dìfang", "m": "Địa điểm/Nơi chốn"},
    {"h": "地铁", "p": "dìtiě", "m": "Tàu điện ngầm"}, {"h": "地图", "p": "dìtú", "m": "Bản đồ"},
    {"h": "电梯", "p": "diàntī", "m": "Thang máy"}, {"h": "电子邮件", "p": "diànzǐ yóujiàn", "m": "Email"},
    {"h": "东", "p": "dōng", "m": "Phía Đông"}, {"h": "冬", "p": "dōng", "m": "Mùa đông"},
    {"h": "放", "p": "fàng", "m": "Đặt/Để/Thả"},
    {"h": "动物", "p": "dòngwù", "m": "Động vật"}, {"h": "短", "p": "duǎn", "m": "Ngắn"},
    {"h": "段", "p": "duàn", "m": "Đoạn/Khoảng"}, {"h": "锻炼", "p": "duànliàn", "m": "Tập thể dục/Rèn luyện"},
    {"h": "多么", "p": "duōme", "m": "Biết bao nhiêu"}, {"h": "饿", "p": "è", "m": "Đói"},
    {"h": "耳朵", "p": "ěrduo", "m": "Cái tai"}, {"h": "发", "p": "fā", "m": "Gửi (email, tin nhắn)"},
    {"h": "放心", "p": "fàngxīn", "m": "Yên tâm"}, {"h": "分", "p": "fēn", "m": "Phút/Điểm"},
    {"h": "附近", "p": "fùjìn", "m": "Lân cận/Gần đây"}, {"h": "复习", "p": "fùxí", "m": "Ôn tập"},
    {"h": "敢", "p": "gǎn", "m": "Dám"}, {"h": "感冒", "p": "gǎnmào", "m": "Cảm cúm"},
    {"h": "根据", "p": "gēnjù", "m": "Căn cứ vào"}, {"h": "跟", "p": "gēn", "m": "Cùng/Với"},
    {"h": "更", "p": "gèng", "m": "Càng/Hơn"}, {"h": "公共汽车", "p": "gōnggòng qìchē", "m": "Xe buýt"},
    {"h": "公斤", "p": "gōngjīn", "m": "Kilôgam (kg)"}, {"h": "公司", "p": "gōngsī", "m": "Công ty"},
    {"h": "公园", "p": "gōngyuán", "m": "Công viên"}, {"h": "关", "p": "guān", "m": "Đóng/Tắt"},
    {"h": "关系", "p": "guānxi", "m": "Quan hệ/Liên quan"}, {"h": "关心", "p": "guānxīn", "m": "Quan tâm"},
    {"h": "关于", "p": "guānyú", "m": "Về/Liên quan đến"},
    {"h": "国家", "p": "guójiā", "m": "Quốc gia"}, {"h": "果汁", "p": "guǒzhī", "m": "Nước trái cây"},
    {"h": "过去", "p": "guòqù", "m": "Quá khứ/Trước đây"}, {"h": "害怕", "p": "hàipà", "m": "Sợ hãi"},
    {"h": "航班", "p": "hángbān", "m": "Chuyến bay"}, {"h": "黑板", "p": "hēibǎn", "m": "Bảng đen"},
    {"h": "后来", "p": "hòulái", "m": "Sau đó (quá khứ)"}, {"h": "护照", "p": "hùzhào", "m": "Hộ chiếu"},
    {"h": "花", "p": "huā", "m": "Hoa/Tiêu (tiền, thời gian)"}, {"h": "坏", "p": "huài", "m": "Hỏng/Xấu"},
    {"h": "欢迎", "p": "huānyíng", "m": "Chào mừng"}, {"h": "环境", "p": "huánjìng", "m": "Môi trường"},
    {"h": "换", "p": "huàn", "m": "Đổi/Thay"}, {"h": "黄", "p": "huáng", "m": "Màu vàng"},
    {"h": "会议", "p": "huìyì", "m": "Cuộc họp/Hội nghị"}, {"h": "或者", "p": "huòzhě", "m": "Hoặc là (trần thuật)"},
    {"h": "机会", "p": "jīhuì", "m": "Cơ hội"}, {"h": "极", "p": "jí", "m": "Cực kỳ"},
    {"h": "季节", "p": "jìjié", "m": "Mùa"}, {"h": "见面", "p": "jiànmiàn", "m": "Gặp mặt"},
    {"h": "健康", "p": "jiànkāng", "m": "Khỏe mạnh"}, {"h": "讲", "p": "jiǎng", "m": "Nói/Giảng/Kể"},
    {"h": "角", "p": "jiǎo", "m": "Hào (tiền tệ)"}, {"h": "脚", "p": "jiǎo", "m": "Bàn chân"},
    {"h": "接", "p": "jiē", "m": "Đón/Nhận (điện thoại)"},
    {"h": "离开", "p": "líkāi", "m": "Rời khỏi"}, {"h": "脸", "p": "liǎn", "m": "Khuôn mặt"},
    {"h": "辆", "p": "liàng", "m": "Chiếc/Cái (xe)"}, {"h": "聊天", "p": "liáotiān", "m": "Tán gẫu"},
    {"h": "了解", "p": "liǎojiě", "m": "Hiểu rõ"}, {"h": "邻居", "p": "línjū", "m": "Hàng xóm"},
    {"h": "留学", "p": "liúxué", "m": "Du học"}, {"h": "楼", "p": "lóu", "m": "Tòa nhà/Tầng"},
    {"h": "绿", "p": "lǜ", "m": "Màu xanh lá cây"},
    {"h": "马", "p": "mǎ", "m": "Con ngựa"}, {"h": "满意", "p": "mǎnyì", "m": "Hài lòng"},
    {"h": "帽子", "p": "màozi", "m": "Cái mũ"}, {"h": "米", "p": "mǐ", "m": "Gạo/Mét"},
    {"h": "面包", "p": "miànbāo", "m": "Bánh mì"}, {"h": "面条", "p": "miàntiáo", "m": "Mì sợi"},
    {"h": "拿", "p": "ná", "m": "Cầm/Lấy"}, {"h": "奶奶", "p": "nǎinai", "m": "Bà nội"},
    {"h": "南", "p": "nán", "m": "Phía Nam"}, {"h": "难", "p": "nán", "m": "Khó"},
    {"h": "难过", "p": "nánguò", "m": "Buồn bã"}, {"h": "年级", "p": "niánjí", "m": "Lớp/Khối"},
    {"h": "年轻", "p": "niánqīng", "m": "Trẻ trung"}, {"h": "鸟", "p": "niǎo", "m": "Con chim"},
    {"h": "努力", "p": "nǔlì", "m": "Nỗ lực"}, {"h": "爬山", "p": "páshān", "m": "Leo núi"},
    {"h": "盘子", "p": "pánzi", "m": "Cái đĩa"}, {"h": "啤酒", "p": "píjiǔ", "m": "Bia"},
    {"h": "便宜", "p": "piányi", "m": "Rẻ"}, {"h": "票", "p": "piào", "m": "Vé"},
    {"h": "普通话", "p": "pǔtōnghuà", "m": "Tiếng phổ thông"}, {"h": "骑", "p": "qí", "m": "Cưỡi/Đi (xe)"},
    {"h": "其实", "p": "qíshí", "m": "Thực ra"}, {"h": "其他", "p": "qítā", "m": "Cái khác/Người khác"},
    {"h": "起飞", "p": "qǐfēi", "m": "Cất cánh"},

    # Nhóm 8-10 
    {"h": "起来", "p": "qǐlái", "m": "Dậy/Đứng dậy"}, {"h": "清楚", "p": "qīngchu", "m": "Rõ ràng"},
    {"h": "请假", "p": "qǐngjià", "m": "Xin nghỉ"}, {"h": "秋", "p": "qiū", "m": "Mùa thu"},
    {"h": "裙子", "p": "qúnzi", "m": "Cái váy"}, {"h": "然后", "p": "ránhòu", "m": "Sau đó"},
    {"h": "认为", "p": "rènwéi", "m": "Cho rằng"}, {"h": "认真", "p": "rènzhēn", "m": "Chăm chỉ/Nghiêm túc"},
    {"h": "容易", "p": "róngyì", "m": "Dễ dàng"}, {"h": "如果", "p": "rúguǒ", "m": "Nếu"},
    {"h": "伞", "p": "sǎn", "m": "Cái ô/dù"}, {"h": "上网", "p": "shàngwǎng", "m": "Lên mạng"},
    {"h": "世界", "p": "shìjiè", "m": "Thế giới"}, {"h": "试", "p": "shì", "m": "Thử"},
    {"h": "瘦", "p": "shòu", "m": "Gầy"}, {"h": "叔叔", "p": "shūshu", "m": "Chú"},
    {"h": "树", "p": "shù", "m": "Cái cây"}, {"h": "数学", "p": "shùxué", "m": "Toán học"},
    {"h": "刷牙", "p": "shuāyá", "m": "Đánh răng"}, {"h": "双", "p": "shuāng", "m": "Đôi/Cặp"},
    {"h": "水平", "p": "shuǐpíng", "m": "Trình độ"}, {"h": "司机", "p": "sījī", "m": "Tài xế"},
    {"h": "虽然", "p": "suīrán", "m": "Mặc dù"}, {"h": "糖", "p": "táng", "m": "Kẹo/Đường"},
    {"h": "疼", "p": "téng", "m": "Đau"},
    {"h": "提高", "p": "tígāo", "m": "Nâng cao"}, {"h": "体育", "p": "tǐyù", "m": "Thể dục/Thể thao"},
    {"h": "甜", "p": "tián", "m": "Ngọt"}, {"h": "条
